version: '3'

services:
  db:
    image: mongo:4.2
    volumes:
      - db:/data/db/

  rita:
    image: quay.io/activecm/rita:${VERSION:-latest}
    links:
      - db:localhost
    volumes:
      - ./rita-docker.yaml:/etc/rita/config.yaml:ro
      - ./output:/logs:ro

volumes:
  db:
